# Generated by Django 4.2.4 on 2023-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_gasstation_profile_email_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('Issuer_number', models.CharField(max_length=200)),
                ('Gas_station_number', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('GPS_coordinates_latitude', models.FloatField()),
                ('GPS_coordinates_longitude', models.FloatField()),
                ('Companion_Service_Objects', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_point', models.CharField(max_length=200)),
                ('end_point', models.CharField(max_length=200)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('axle_load', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
