# Generated by Django 4.2.4 on 2023-08-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gasstation_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='Companion_Service_Objects',
        ),
    ]
