# Generated by Django 4.2.4 on 2023-08-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_gasstation_companion_service_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='axle_load',
        ),
        migrations.RemoveField(
            model_name='route',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='route',
            name='vehicle_height',
        ),
        migrations.AddField(
            model_name='route',
            name='RefuelingOnTheRoute',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
