# Generated by Django 4.2.4 on 2023-08-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_route_axle_load_remove_route_total_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='RefuelingOnTheRoute',
            field=models.TextField(default=''),
        ),
    ]
